// <auto-generated />
namespace pu_system_test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Practices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Practices));
        
        string IMigrationMetadata.Id
        {
            get { return "201806070921014_Practices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
